// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert_service.proto

package ds.alertservice;

public final class AlertServiceImp {
  private AlertServiceImp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Alert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Alert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlertConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlertConfirmation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023alert_service.proto\"=\n\005Alert\022\020\n\010locati" +
      "on\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\021\n\ttimestamp\030\003" +
      " \001(\003\"7\n\021AlertConfirmation\022\017\n\007message\030\001 \001" +
      "(\t\022\021\n\ttimestamp\030\002 \001(\0032j\n\014AlertService\022\'\n" +
      "\tSendAlert\022\006.Alert\032\022.AlertConfirmation\0221" +
      "\n\017BroadcastAlerts\022\006.Alert\032\022.AlertConfirm" +
      "ation(\0010\001B$\n\017ds.alertserviceB\017AlertServi" +
      "ceImpP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Alert_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Alert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Alert_descriptor,
        new java.lang.String[] { "Location", "Message", "Timestamp", });
    internal_static_AlertConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AlertConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlertConfirmation_descriptor,
        new java.lang.String[] { "Message", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
