// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert_service.proto

package ds.alertservice;

public interface AlertSubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AlertSubscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
