// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert_service.proto

package ds.alertservice;

public interface AlertConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AlertConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();
}
