// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollution_sensor_service.proto

package ds.pollutionsensorservice;

public interface GetAveragePollutionDataResponceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAveragePollutionDataResponce)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 average = 1;</code>
   */
  int getAverage();
}
