// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollution_sensor_service.proto

package ds.pollutionsensorservice;

public interface PollutionDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>double air_pollution = 2;</code>
   */
  double getAirPollution();

  /**
   * <code>double water_pollution = 3;</code>
   */
  double getWaterPollution();

  /**
   * <code>int64 timestamp = 4;</code>
   */
  long getTimestamp();
}
