// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollution_sensor_service.proto

package ds.pollutionsensorservice;

public interface PollutionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
