// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollution_sensor_service.proto

package ds.pollutionsensorservice;

public final class PollutionSensorServiceImp {
  private PollutionSensorServiceImp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPollutionDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPollutionDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCityMultiplePollutionDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCityMultiplePollutionDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAveragePollutionDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAveragePollutionDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036pollution_sensor_service.proto\"+\n\027GetP" +
      "ollutionDataRequest\022\020\n\010location\030\001 \001(\t\"L\n" +
      "#GetCityMultiplePollutionDataRequest\022\020\n\010" +
      "location\030\001 \001(\t\022\023\n\013num_of_days\030\002 \001(\005\"b\n\036G" +
      "etAveragePollutionDataRequest\022\020\n\010locatio" +
      "n\030\001 \001(\t\022\025\n\rair_pollution\030\002 \001(\001\022\027\n\017water_" +
      "pollution\030\003 \001(\001\"d\n\rPollutionData\022\020\n\010loca" +
      "tion\030\001 \001(\t\022\025\n\rair_pollution\030\002 \001(\001\022\027\n\017wat" +
      "er_pollution\030\003 \001(\001\022\021\n\ttimestamp\030\004 \001(\0032\374\001" +
      "\n\026PollutionSensorService\022<\n\020GetPollution" +
      "Data\022\030.GetPollutionDataRequest\032\016.Polluti" +
      "onData\022V\n\034GetCityMultiplePollutionData\022$" +
      ".GetCityMultiplePollutionDataRequest\032\016.P" +
      "ollutionData0\001\022L\n\027GetAveragePollutionDat" +
      "a\022\037.GetAveragePollutionDataRequest\032\016.Pol" +
      "lutionData(\001B8\n\031ds.pollutionsensorservic" +
      "eB\031PollutionSensorServiceImpP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetPollutionDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetPollutionDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPollutionDataRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_GetCityMultiplePollutionDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetCityMultiplePollutionDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCityMultiplePollutionDataRequest_descriptor,
        new java.lang.String[] { "Location", "NumOfDays", });
    internal_static_GetAveragePollutionDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAveragePollutionDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAveragePollutionDataRequest_descriptor,
        new java.lang.String[] { "Location", "AirPollution", "WaterPollution", });
    internal_static_PollutionData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PollutionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionData_descriptor,
        new java.lang.String[] { "Location", "AirPollution", "WaterPollution", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
