// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollution_analysis_service.proto

package ds.pollutionanalysisservice;

public interface LiveTrendsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LiveTrendsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string locations = 1;</code>
   */
  java.util.List<java.lang.String>
      getLocationsList();
  /**
   * <code>repeated string locations = 1;</code>
   */
  int getLocationsCount();
  /**
   * <code>repeated string locations = 1;</code>
   */
  java.lang.String getLocations(int index);
  /**
   * <code>repeated string locations = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationsBytes(int index);
}
