// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollution_analysis_service.proto

package ds.pollutionanalysisservice;

public interface PollutionAnalysisOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionAnalysis)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string trend = 2;</code>
   */
  java.lang.String getTrend();
  /**
   * <code>string trend = 2;</code>
   */
  com.google.protobuf.ByteString
      getTrendBytes();
}
