// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollution_analysis_service.proto

package ds.pollutionanalysisservice;

public interface TrendingLocationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrendingLocations)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string locations = 1;</code>
   */
  java.lang.String getLocations();
  /**
   * <code>string locations = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationsBytes();
}
