// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollution_analysis_service.proto

package ds.pollutionanalysisservice;

public interface TrendingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrendingRequest)
    com.google.protobuf.MessageOrBuilder {
}
